"""Changed user password field name

Revision ID: 350db25f0123
Revises: b1b1cec35c99
Create Date: 2026-03-03 13:03:51.470435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '350db25f0123'
down_revision = 'b1b1cec35c99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
